name: Lua Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Compiler
        working-directory: ./12/lua-5.4.8
        run: pwd && make

      - name: Run Benchmark
        run: ./12/lua-5.4.8/src/lua ./12/lua/fib.lua > benchmark_results.txt

      - name: Store Benchmark Results
        uses: actions/upload-artifact@v3
        with:
          name: raw-benchmark-log
          output-file-path: "benchmark_results.txt"
