name: Lua Benchmark

on: [push]

jobs:
 benchmark: 
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v3
   - name: Checkout
  
   - name: Setup Lua
   - uses: leafo/gh-actions-lua@v9
     with:
       lua-version: "5.4"
  
   - name: Build Compiler
     run: cd ./sheet12/lua-5.4.8 && make
  
   - name: Run Benchmark
     run: ./sheet12/lua-5.4.8/lua sheet12/lua/fib.lua > benchmark_results.txt
     
   - uses: benchmark-action/github-action-benchmark@v1
   - name: Store Benchmark Results
     with:
       name: "Lua Benchmark"
       tool: 'lua'
       output-file-path: 'benchmark_results.txt'
