name: Lua Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build Compiler
        working-directory: sheet12/lua-5.4.8
        run: make

      - name: Run Benchmark
        run: ./sheet12/lua-5.4.8/src/lua sheet12/lua/fib.lua > benchmark_results.txt

      - name: Store Benchmark Results
        uses: benchmark-action/github-action-benchmark@v1
        with:
          name: "Lua Benchmark"
          tool: "lua"
          output-file-path: "benchmark_results.txt"
