name: Lua Benchmark

on: [push]

jobs:
  benchmark:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install bc
        run: sudo apt-get update && sudo apt-get install -y bc

      - name: Build Lua
        working-directory: ./12/lua-5.4.8
        run: make

      - name: Make benchmark script executable
        run: chmod +x ./12/benchmark.sh

      - name: Run Benchmark Script
        working-directory: ./12
        run: ./benchmark.sh

      - name: Commit and Push Results
        run: |
          git config set advice.addIgnoredFile false || true
          git config --global user.name 'GitHub Actions Bot'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

          # Add result files
          git add 12/results_github_actions/benchmark-*.txt
          git add 12/results_github_actions/benchmark_results.csv

          # Commit and push if there are changes
          if ! git diff --staged --quiet; then
            git commit -m "chore: Add benchmark results for ${{ github.sha }}" -m "[skip ci]"
            git push
          else
            echo "No new benchmark results to commit."
          fi